import Providers from "@/components/provider/provider";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/header.jsx/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pinterest-Clone-Akashsrma369",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
